trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: InstallMATLAB@0
    # default to latest version of Matlab installed
    #inputs:
    #  release: R2020a
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip 
      pip install pynwb
    displayName: 'Install PyNWB'

  - task: RunMATLABCommand@0
    inputs:
      command: "try, results = nwbtest; if isempty(results), exit(1); end; catch err, disp(err.message); exit(1); end"
  
