trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: InstallMATLAB@0
    # default to latest version of Matlab installed
    #inputs:
    #  release: R2020a
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip 
      pip install pynwb
      pip install hdf5plugin
      echo "##vso[task.setvariable variable=HDF5_PLUGIN_PATH]$(python -c "import hdf5plugin; print(hdf5plugin.PLUGINS_PATH)")"
    displayName: 'Install PyNWB'

  - bash: |
      echo "$(HDF5_PLUGIN_PATH)"

  - task: RunMATLABCommand@0
    inputs:
      command: "results = assertSuccess(nwbtest); assert(~isempty(results), 'No tests ran');"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: testResults.xml
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: coverage.xml
      
  - script: |
      bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload coverage to codecov'

  
